liip_imagine:
#    # valid drivers options include "gd" or "gmagick" or "imagick"
#    driver: "gd"
#
#    # define your filter sets under this option
    filter_sets:
        thumbnail_gallery:
            filters:
                thumbnail:
                    size:          [400, 300]
                    mode:          outbound
                    allow_upscale: true

#
#        # an example thumbnail transformation definition
#        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
#
#            # set your image quality defaults
#            jpeg_quality:          85
#            png_compression_level: 8
#
#            # setup the filter steps to apply for this transformation
#        my_watermark_filter:
#            filters:
#                # use and setup the "watermark" filter
#                watermark:
#
#                    # path to the watermark file (prepended with "%kernel.root_dir%")
#                    image: Resources/data/logo.png
#
#                    # size of the water mark relative to the input image
#                    size: 0.5
#
#                    # set the position of the watermark
#                    position: center
#
#                thumbnail:
#                    size:          [400,300]
#                    mode:          outbound
#                    allow_upscale: true
#
#                # auto rotate the image using EXIF metadata
#                auto_rotate: ~
#
#                # strip the image of all metadata
#                strip: ~
#
#                # scale and square the image to the given dimensions
#                thumbnail:
#                    size:          [253, 253]
#                    mode:          outbound
#                    allow_upscale: true
#
#                # create border by placing image on larger black background
#                background:
#                    size:     [256, 256]
#                    position: center
#                    color:    '#fff'
