# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        thumbnail_gallery:
            filters:
                thumbnail:
                    size:          [400, 300]
                    mode:          outbound
                    allow_upscale: true

        watermark_pictures:
            filters:
                watermark_image:
                    # path to the watermark file (prepended with "%kernel.root_dir%")
                    image: "/public/images/logoBig.png"
                    # size of the water mark relative to the input image
                    size: 0.25
                    # set the position of the watermark
                    position: bottomright
